# -*- coding: utf-8 -*-
"""experiment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F2ubQOKjN4t3JWSZKxJ07mOTAedJXa-9
"""

import pandas as pd
import numpy as np
import sklearn 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

url = "MOCK_DATA.csv"
df = pd.read_csv(url)
y = df["Outcome"]
df.drop(["Outcome", "wrong", "IP Adress"], axis=1, inplace=True)
df['Gender'] = df['Gender'].map({'M': 0, 'F':1})
X = df
print(X.head())
print('Labels: ')
print(y.head())

""""col_names = ["height", "weight", "gender", "age", "exercise_freq", "knowledge", "diet", "history", "inheritance"]
df = pd.DataFrame(np.random.randint(0,200,size=(200, len(col_names))), columns=col_names)
df.head()
X = df"""

'''to_bool = lambda x: x > 0.5
y = to_bool(np.random.rand(200))'''

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.33, random_state=42)

estimator = DecisionTreeClassifier(max_depth=3, min_samples_leaf=5)
estimator.fit(X_train.values, y_train)



prediction = estimator.predict(X_test.values)

accuracy_score(y_test, prediction)

rnum = 3
record = X_test.iloc[rnum].values
estimator.predict([record])



"""record = np.array([1, 2.3, 2])
estimator.predict([record])"""

from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import tree
from sklearn.datasets import load_wine
from IPython.display import SVG
from graphviz import Source
from IPython.display import display


graph = Source(tree.export_graphviz(estimator, out_file=None
   , feature_names=df.columns, class_names=['0', '1', '2'] 
   , filled = True))
display(SVG(graph.pipe(format='svg')))

